$(function($){
    $('#city-1').click(function(){
        $('#city-1-content').toggle();
    });
  $('#city-2').click(function(){
        $('#city-2-content').toggle();
    });
  $('#city-3').click(function(){
        $('#city-3-content').toggle();
    });
  $('#city-4').click(function(){
        $('#city-4-content').toggle();
    });
  $('#city-5').click(function(){
        $('#city-5-content').toggle();
    });
  $('#city-6').click(function(){
        $('#city-6-content').toggle();
    });
});